name: Build Web API .NET 9

on:
  push:
    branches: [ "**" ] # Trigger on any push to any branch

  pull_request:
    branches: [ "**" ] # Trigger on any pull request to any branch
    types: [ closed, synchronize, opened, edited, reopened ] # Trigger when a pull request is closed (including merges)
        
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish DocumentsWebApi/DocumentsWebApi.csproj -c Release -o publish

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: . # Dockerfile is in the root
        file: ./Dockerfile
        push: false # Set to true to push to a registry in a later step
        tags: huanhvhd/documents-webapi:latest

  push-to-dockerhub:
    name: Push to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    #if: github.event_name == 'push' # Only push on actual pushes

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set Docker Image Tag
      id: docker_tag
      run: |
        BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed -e 's/\//-/g')
        TIMESTAMP=$(date +%y%m%d%H%M%S)
        IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/documents-webapi:${BRANCH_NAME}-${TIMESTAMP}"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.docker_tag.outputs.IMAGE_TAG }}